### ISSUE TITLE
Makefile now in master QA tarball skeleton

### ISSUE THREAD

**Issue by phil-davis** [owncloud/example-files#6]
Since commit https://github.com/owncloud/example-files/commit/936975ecdffc36a4f0fa615f8367c0ac954df553 the master QA tarball https://download.owncloud.org/community/owncloud-daily-master-qa.tar.bz2 now has:
```
/owncloud/core/skeleton/Makefile
```
In addition to `ownCloud Manual.pdf` and the `Documents` and `Photos` folders.

This is causing unit test fails in the `encryption` app, e.g. https://drone.owncloud.com/owncloud/encryption/619/153
```
There were 3 failures:

1) OCA\Encryption\Tests\Command\FixEncryptedVersionTest::testEncryptedVersionZero
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Verifying the content of file /test_enc_version_affected_user1/files/hello.txt\n
+'Verifying the content of file /test_enc_version_affected_user1/files/Makefile\n
+The file /test_enc_version_affected_user1/files/Makefile is: OK\n
+Verifying the content of file /test_enc_version_affected_user1/files/hello.txt\n

/var/www/owncloud/server/apps/encryption/tests/unit/Command/FixEncryptedVersionTest.php:147

2) OCA\Encryption\Tests\Command\FixEncryptedVersionTest::testEncryptedVersionLessThanOriginalValue
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Verifying the content of file /test_enc_version_affected_user1/files/foo.txt\n
+'Verifying the content of file /test_enc_version_affected_user1/files/Makefile\n
+The file /test_enc_version_affected_user1/files/Makefile is: OK\n
+Verifying the content of file /test_enc_version_affected_user1/files/foo.txt\n

/var/www/owncloud/server/apps/encryption/tests/unit/Command/FixEncryptedVersionTest.php:231

3) OCA\Encryption\Tests\Command\FixEncryptedVersionTest::testEncryptedVersionGreaterThanOriginalValue
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Verifying the content of file /test_enc_version_affected_user1/files/foo.txt\n
+'Verifying the content of file /test_enc_version_affected_user1/files/Makefile\n
+The file /test_enc_version_affected_user1/files/Makefile is: OK\n
+Verifying the content of file /test_enc_version_affected_user1/files/foo.txt\n

/var/www/owncloud/server/apps/encryption/tests/unit/Command/FixEncryptedVersionTest.php:316

FAILURES!
Tests: 241, Assertions: 704, Failures: 3.

Generating code coverage report in Clover XML format ... done
Makefile:70: recipe for target 'test-php-unit-dbg' failed
make: *** [test-php-unit-dbg] Error 1 
```
because when doing a general encryption `occ` command for a user, there is now the file `Makefile` to be processed.

**Comment by phil-davis** [comment]
@PVince81 this problem does not happen in the `stable10` QA tarball. I guess that is because there is a `stable10` branch here in the `example-files` repo. And that branch does not have `Makefile` added.

Whatever happens, probably we should amke `stable10` and `master` branch here the same.

Maybe if we build a release, we are going to end up with `Makefile` appearing in the default skeleton?

Anyway, whatever builds the QA tarball needs to be smarter about creating `core/skeleton` from this repo. Maybe the QA tarball creation script should now use `make dist` here in this repo to make an `example-files` tarball, then unpack that. Because `make dist` is correctly not putting `Makefile` into the tarball.

**Comment by PVince81** [comment]
we'll use Github releases from now on, the release script has been adjusted to grab from Github releases for stable10. For master it still builds with Makefiles.

the adjusted release script hasn't been activated yes, will do soon

**Comment by PVince81** [comment]
should be solved now, closing
